'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';import Nav from '@/components/Nav';import {supabase} from '@/lib/supabase';
type U={id:string;nome:string;role:string;email:string;created_at:string;last_sign_in_at:string|null};const roles=['ADMIN','NIVALDO','RAFAEL','ELZA'];
export default function Page(){const db=useMemo(()=>supabase(),[]);const[rows,setRows]=useState<U[]>([]),[msg,setMsg]=useState(''),[open,setOpen]=useState(false),[edit,setEdit]=useState<U|null>(null),[f,setF]=useState({nome:'',email:'',role:'ELZA',password:''}),[reset,setReset]=useState<U|null>(null),[senha,setSenha]=useState(''),[view,setView]=useState<U|null>(null);
async function load(){const{data,error}=await db.rpc('list_panel_users');if(error)setMsg('Não foi possível carregar usuários.');else setRows((data??[])as U[])}useEffect(()=>{load()},[]);
async function token(){const{data}=await db.auth.getSession();return data.session?.access_token}
async function api(body:unknown){const tk=await token();const r=await fetch('/api/admin/manage-user',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${tk}`},body:JSON.stringify(body)});return {ok:r.ok,data:await r.json()}}
function novo(){setView(null);setEdit(null);setF({nome:'',email:'',role:'ELZA',password:''});setOpen(true)}function visualizar(u:U){setOpen(false);setReset(null);setView(u)}function editar(u:U){setView(null);setEdit(u);setF({nome:u.nome,email:u.email,role:u.role,password:''});setOpen(true)}
async function salvar(e:FormEvent){e.preventDefault();const body=edit?{action:'update',userId:edit.id,nome:f.nome,role:f.role}:{action:'create',...f};const r=await api(body);if(!r.ok)return setMsg(r.data.error||'Falha ao salvar.');setOpen(false);setMsg(edit?'Usuário atualizado.':'Usuário criado.');load()}
async function excluir(u:U){if(!confirm(`Excluir o acesso de ${u.nome}?`))return;const r=await api({action:'delete',userId:u.id});setMsg(r.ok?'Usuário excluído.':r.data.error||'Não foi possível excluir.');if(r.ok)load()}
async function redefinir(){if(!reset||senha.length<8)return setMsg('A senha deve ter pelo menos 8 caracteres.');const tk=await token();const r=await fetch('/api/admin/reset-password',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${tk}`},body:JSON.stringify({userId:reset.id,novaSenha:senha})});const d=await r.json();setMsg(r.ok?'Senha redefinida.':d.error||'Falha ao redefinir.');if(r.ok){setReset(null);setSenha('')}}
return <div className="shell"><Nav/><main className="content"><header><div><span className="eyebrow">ADMINISTRAÇÃO NT ALPHA</span><h1>Usuários</h1><p className="page-intro">Criação, perfil, senha e exclusão de acessos.</p></div><button onClick={novo}>+ Novo usuário</button></header>{msg&&<div className="status">{msg}</div>}
{view&&<section className="panel"><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'flex-start',flexWrap:'wrap'}}><div><span className="eyebrow">CADASTRO DO USUÁRIO</span><h2 style={{marginBottom:4}}>{view.nome}</h2><p className="page-intro" style={{margin:0}}>Visualização somente leitura.</p></div><div className="actions"><button onClick={()=>editar(view)}>Editar cadastro</button><button className="secondary-button" onClick={()=>setView(null)}>← Voltar para usuários</button></div></div><div className="grid" style={{marginTop:22}}><div><small>E-mail</small><br/><strong>{view.email}</strong></div><div><small>Perfil</small><br/><strong>{view.role}</strong></div><div><small>Último acesso</small><br/><strong>{view.last_sign_in_at?new Date(view.last_sign_in_at).toLocaleString('pt-BR'):'Ainda não acessou'}</strong></div></div></section>}{open&&<section className="panel form quick-form"><h2>{edit?'Editar usuário':'Novo usuário'}</h2><form onSubmit={salvar}><div className="grid"><label>Nome<input required value={f.nome} onChange={e=>setF({...f,nome:e.target.value})}/></label><label>E-mail<input type="email" required disabled={!!edit} value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Perfil<select value={f.role} onChange={e=>setF({...f,role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label>{!edit&&<label>Senha inicial<input type="password" minLength={8} required value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></label>}</div><div className="actions"><button>Salvar</button><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button></div></form></section>}
<section className="panel"><div className="data-list">{rows.map(u=><article className="data-card user-crud-card" key={u.id}><div><strong>{u.nome}</strong><span>{u.email}</span></div><div><small>Perfil</small><b>{u.role}</b></div><div className="row-actions"><button className="secondary-button" onClick={()=>visualizar(u)}>Visualizar</button><button onClick={()=>editar(u)}>Editar</button><button onClick={()=>{setReset(u);setSenha('')}}>Senha</button><button className="danger-button" onClick={()=>excluir(u)}>Excluir</button></div></article>)}</div></section>
{reset&&<div className="password-modal-backdrop"><div className="password-modal"><h2>Redefinir senha</h2><p><strong>{reset.nome}</strong><br/>{reset.email}</p><label>Nova senha<input type="password" minLength={8} value={senha} onChange={e=>setSenha(e.target.value)}/></label><div className="password-modal-actions"><button className="cancel" onClick={()=>setReset(null)}>Cancelar</button><button className="confirm" onClick={redefinir}>Redefinir senha</button></div></div></div>}
</main></div>}