'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';import Nav from '@/components/Nav';import {supabase} from '@/lib/supabase';
type P={id:string;codigo:string|null;titulo:string;tipo:string;cidade:string|null;bairro:string|null;endereco:string|null;valor:number|null;dormitorios:number;suites:number;vagas:number;area_util:number|null;descricao:string|null;status:string;destaque:boolean;publicar_site:boolean};
export default function Imoveis(){const db=useMemo(()=>supabase(),[]);const[rows,setRows]=useState<P[]>([]),[busca,setBusca]=useState(''),[status,setStatus]=useState(''),[edit,setEdit]=useState<P|null>(null),[msg,setMsg]=useState('');
async function load(){const{data,error}=await db.from('properties').select('*').order('created_at',{ascending:false});if(error)setMsg('Erro ao carregar: '+error.message);else setRows((data??[]) as P[])}useEffect(()=>{load()},[]);
async function salvar(e:FormEvent){e.preventDefault();if(!edit)return;const{data:{user}}=await db.auth.getUser();const{error}=await db.from('properties').update({...edit,updated_by:user?.id??null}).eq('id',edit.id);if(error)return setMsg('Não foi possível atualizar: '+error.message);setEdit(null);setMsg('Imóvel atualizado.');load()}
async function excluir(p:P){if(!confirm(`Excluir ${p.codigo??''} - ${p.titulo}? Esta ação não pode ser desfeita.`))return;const{error}=await db.from('properties').delete().eq('id',p.id);if(error)return setMsg('Não foi possível excluir. O imóvel pode possuir histórico/vínculos. Use status Inativo quando necessário.');setMsg('Imóvel excluído.');load()}
const list=rows.filter(p=>(!status||p.status===status)&&[p.codigo,p.titulo,p.bairro,p.cidade].join(' ').toLowerCase().includes(busca.toLowerCase()));
return <div className="shell"><Nav/><main className="content"><header><div><span className="eyebrow">CADASTROS</span><h1>Imóveis</h1><p className="page-intro">Cadastre, consulte, edite, inative ou exclua imóveis.</p></div><a className="button" href="/imoveis/novo">+ Novo imóvel</a></header>
{msg&&<div className="status">{msg}</div>}{edit&&<section className="panel form quick-form"><h2>Editar {edit.codigo}</h2><form onSubmit={salvar}><div className="grid"><label>Título<input required value={edit.titulo} onChange={e=>setEdit({...edit,titulo:e.target.value})}/></label><label>Status<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}><option value="disponivel">Disponível</option><option value="reservado">Reservado</option><option value="vendido">Vendido</option><option value="inativo">Inativo</option></select></label><label>Cidade<input value={edit.cidade??''} onChange={e=>setEdit({...edit,cidade:e.target.value})}/></label><label>Bairro<input value={edit.bairro??''} onChange={e=>setEdit({...edit,bairro:e.target.value})}/></label><label>Valor<input type="number" value={edit.valor??''} onChange={e=>setEdit({...edit,valor:e.target.value?Number(e.target.value):null})}/></label><label>Área útil<input type="number" value={edit.area_util??''} onChange={e=>setEdit({...edit,area_util:e.target.value?Number(e.target.value):null})}/></label></div><div className="checks"><label><input type="checkbox" checked={edit.destaque} onChange={e=>setEdit({...edit,destaque:e.target.checked})}/> Destaque</label><label><input type="checkbox" checked={edit.publicar_site} onChange={e=>setEdit({...edit,publicar_site:e.target.checked})}/> Publicar no site</label></div><div className="actions"><button>Salvar alterações</button><button type="button" className="secondary-button" onClick={()=>setEdit(null)}>Cancelar</button></div></form></section>}
<section className="panel"><div className="toolbar"><input placeholder="Buscar por código, título ou bairro" value={busca} onChange={e=>setBusca(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option><option value="disponivel">Disponível</option><option value="reservado">Reservado</option><option value="vendido">Vendido</option><option value="inativo">Inativo</option></select></div>{list.length===0?<div className="empty"><b>Nenhum imóvel encontrado.</b></div>:<div className="data-list">{list.map(p=><article className="data-card crud-card" key={p.id}><div><strong>{p.codigo??'Código automático'} · {p.titulo}</strong><span>{p.bairro??'—'} · {p.cidade??'—'}</span></div><div><small>Status</small><b>{p.status}</b></div><div className="row-actions"><button onClick={()=>setEdit(p)}>Editar</button><button className="danger-button" onClick={()=>excluir(p)}>Excluir</button></div></article>)}</div>}</section></main></div>}